#!/bin/sh

case "$1" in
  setup)

    read -p "Enter the Platform.sh project ID: " platformid
    platform get $platformid project

    if [ -d ".vagrant" ]; then
      vagrant reload --provision
    else
      vagrant up
    fi
    ;;
  *)
    echo "Usage: $0 {setup}"
    exit 1
esac
